### ISSUE TITLE
Integrate with Symfony console

### ISSUE THREAD

**Issue by eydun** [thephpleague/climate#167]
Climate looks better than Symfony console, which most projects use. 

Would it make sense to integrate Climate with Symfony console, or how do they compare?

**Comment by duncan3dc** [comment]
Hi @eydun I actually first started out with CLImate by integrating it into Symfony Console.
I have a separate library that maintains compatibility between the two: https://github.com/duncan3dc/symfony-climate
I also have an extension to Symfony Console that wires up the above along with some other extensions: https://github.com/duncan3dc/console

That was back when CLImate was output focussed, since then CLImate has started to build more input handling and command management, making it a viable alternative to Symfony Console, such that I no longer think it makes sense to try to integrate the two.

Now I think the focus should be on adding any missing functionality to CLImate that is useful in a full console application context.
I welcome any PRs or feature requests in that direction. Thanks!

**Comment by eydun** [comment]
Thank you for the explanation, and thank you for great work you are doing!
