### ISSUE TITLE
Is it really need to instantiate CLImate object every time it needed?

### ISSUE THREAD

**Issue by gugglegum** [thephpleague/climate#180]
Why not to use static methods? Maybe I missed something but the console is always only one. So we have no obvious profit when doing it dynamic.

**Comment by duncan3dc** [comment]
CLImate is instance based to allow for [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection).
As an example, this makes it easy to mock during unit testing, so that we can test our code is working correctly.

Also there is not necessarily always one instance, it's possible to have multiple instances that write to different locations, static methods would not support this
